<section
  data-markdown="/dependency-installers.md"
  data-separator="^\n---\n$"
  data-separator-vertical="^\n--\n$"
></section>
<section
  data-markdown="/virtual-environments.md"
  data-separator="^\n---\n$"
  data-separator-vertical="^\n--\n$"
></section>
